### PR TITLE
Revert "config: Let CMake handle C++11 flags."

### PR DESCRIPTION
**Pull request by xiaoyeli**
Reverts xiaoyeli/superlu_dist#51

### CODE REVIEW

**Comment by xiaoyeli** [comment]
The code cannot work with the C++ compiler that doesn't support c++11 flag.

**Comment by bavier** [comment]
This line from CMakeLists.txt declares to CMake that SuperLU_DIST requires c++11:

https://github.com/xiaoyeli/superlu_dist/blob/74351adc5ca6bc5904be93ed8e9280b4214560f4/CMakeLists.txt#L89 

From that, CMake determines the required flags and is aware of how to handle compilers that support c++11, but require different flags, e.g. `-hstd=c++11` or `--std=c++11`

**Comment by xiaoyeli** [comment]
In principle this should work. But on my Ubuntu, it cannot find this flag
for mpicxx compiler (from MPICH for parallel MPI program).

Sherry Li

**Comment by bavier** [comment]
Yes, I see.  It's possible this worked for me for some other reason.

I would like to see this fixed for the Cray compiler, so I'll look into it some more.

Thanks for testing, and sorry I didn't test on some other platforms before sending.

**Pull request merged**
