### PR TITLE
Try to recover 64-bit indices functionality

### PR DESCRIPTION
**Pull request by nmnobre**
Hi,

I hope I didn't break the code too much. :)
At least on my machine, I can now compile with 64-bit indices through PETSc's `--with-64-bit-indices`.

Cheers,
-Nuno

### CODE REVIEW

**Comment by xiaoyeli** [comment]
Thanks for working on this. 
However, in our new batched code, we deliberately use "int32" for a number of integer vectors, whose values are in [0, N], where N is the dimension of the matrix. We do not expect N will exceed 2^31 (or 2 billion), even though the number of nonzeros in the matrix may exceed 2 billion.  Since the batched code internally calls some older non-batched code, with some fixed "int" vectors, it means that the batched code currently do not work with "int64".

In the future, we plan to change all the code involving O(N) integer vectors to be of type int32. Examples include permutation vectors, etree, etc.  Since there are at least dozens of those types of vectors, int64 type takes a lot of memory. Globally changing this requires a large effort. I cannot predict when this will be done.

I will accept your Python fix.

**Comment by nmnobre** [comment]
Oh! I see... So we're actually going in the opposite direction.

> Thanks for working on this. However, in our new batched code, we deliberately use "int32" for a number of integer vectors, whose values are in [0, N], where N is the dimension of the matrix. We do not expect N will exceed 2^31 (or 2 billion), even though the number of nonzeros in the matrix may exceed 2 billion. Since the batched code internally calls some older non-batched code, with some fixed "int" vectors, it means that the batched code currently do not work with "int64".

But I thought SuperLU has historically supported long indices? And so that the older non-batched code would actually be 64-bit ready?

> In the future, we plan to change all the code involving O(N) integer vectors to be of type int32. Examples include permutation vectors, etree, etc. Since there are at least dozens of those types of vectors, int64 type takes a lot of memory. Globally changing this requires a large effort. I cannot predict when this will be done.

Okay, so can we just remove lines 119 to 122 below, i.e. make the long behave the same as the non-long?

https://github.com/xiaoyeli/superlu_dist/blob/f6023bda87d443b9b351f70314fda77cc7c9436d/SRC/include/superlu_defs.h#L115-L127

Or otherwise how would you go about fixing the situation? We could roll back to a previous version of SuperLU_DIST in the PETSc package spec or no longer pass `-DXSDK_INDEX_SIZE=64` when `--with-64-bit-indices`?

https://gitlab.com/petsc/petsc/-/blob/main/config/BuildSystem/config/packages/SuperLU_DIST.py?ref_type=heads

> I will accept your Python fix.

Happy to cherry-pick, or do you want me create another PR?

**Comment by xiaoyeli** [comment]
All the non-batched code still works with 64-bit indexing, the same as before. But the new batched code only works for 32-bit indexing; it will get run-time error.
In the future, we will go back to the old code, change unnecessary 'int64' to 'int32'. 

If you create a separate PR for the Python fix, that will be great. Thanks!

**Comment by nmnobre** [comment]
Hi Sherry,

Perhaps I got off on the wrong foot, and I would like to better explain the motivation behind this, so we can together arrive at a solution that works for everybody.

So, in essence, if we configure PETSc with gcc 14, which now defaults to `-Werror=incompatible-pointer-types`, and both `--with-64-bit-indices` and `--download-superlu_dist=1`, we get errors like the following:

```
/archive/nnobre/FE/moose/petsc/arch-moose/externalpackages/git.superlu_dist/SRC/prec-independent/get_perm_c_batch.c: In function ‘get_perm_c_batch’:
/archive/nnobre/FE/moose/petsc/arch-moose/externalpackages/git.superlu_dist/SRC/prec-independent/get_perm_c_batch.c:123:33: error: passing argument 6 of ‘get_colamd_dist’ from incompatible pointer type [-Wincompatible-pointer-types]
  123 |                                 perm_c);
      |                                 ^~~~~~
      |                                 |
      |                                 int *
In file included from /archive/nnobre/FE/moose/petsc/arch-moose/externalpackages/git.superlu_dist/SRC/include/superlu_ddefs.h:37,
                 from /archive/nnobre/FE/moose/petsc/arch-moose/externalpackages/git.superlu_dist/SRC/prec-independent/get_perm_c_batch.c:20:
/archive/nnobre/FE/moose/petsc/arch-moose/externalpackages/git.superlu_dist/SRC/include/superlu_defs.h:1108:68: note: expected ‘int_t *’ {aka ‘long int *’} but argument is of type ‘int *’
 1108 |                               int_t *colptr, int_t *rowind, int_t *perm_c);
      |                                                             ~~~~~~~^~~~~~
```

Which, you know, I think it's a fair error to throw because we're mixing pointer types due to the new batch functionality.
This PR just changes the pointer types to 'int_t *' to fix this, and does not break any `int32_t` code/functionality.
This PR would therefore just allow people to compile with `int64_t` with modern compilers.

Now, the code might be wrong or not support `int64_t` at a more fundamental level; but note that with older compilers we're _already_ allowing the compilation of code which uses incompatible pointer types, it's just the compiler isn't erroring out.

I hope this makes more sense now and apologies for not being clearer earlier,
Cheers,
Nuno

**Comment by xiaoyeli** [comment]
I changed the non-batched code to make the 2 permutation vectors to have type 'int', instead of 'int_t'. 
It is pushed in master, and will be in a future release.  Please try 64-bit again.

**Comment by nmnobre** [comment]
Hi @xiaoyeli, yes, it now compiles cleanly. :)
I assume `All the non-batched code still works with 64-bit indexing` is still true after your new changes? In which case, all other code using SuperLU_DIST should still work, same as it did before?

I noticed you removed some trailing white space; as a thank you for your work fixing this issue, I could remove all of the trailing white space, or just from specific folders, e.g. `SRC`, `EXAMPLE` or `TEST`?

**Comment by xiaoyeli** [comment]
Yes, all the non-batched code still works with 64-bit indexing.

We are using a macro system to generate 4 different floating point types of the code, single/double/complex16. It's not productive just to remove the whitespace in the generated code. We will need to do this in the macro base files. This is not a high priority.

**Comment by nmnobre** [comment]
Makes sense. Thank you again for fixing this.

**Pull request closed without merging**
